#!/bin/bash

#dependencies
sudo apt install libimage-exiftool-perl
sudo apt-get install eyed3

#move the startups
sudo cp rbtopopm /usr/local/bin/
sudo cp popmtorb /usr/local/bin/
sudo chmod +x /usr/local/bin/rbtopopm
sudo chmod +x /usr/local/bin/popmtorb
#compile the jars
javac *.java
jar cvf RhythmboxToPOPM.jar RBToPOPM.class
jar cvf POPMToRhythmbox.jar POPMToRB.class ID3Reader.class POPMDecoder.class
#move the jars
sudo cp RhythmboxToPOPM.jar /usr/local/bin/
sudo cp POPMToRhythmbox.jar /usr/local/bin/
