#!/bin/bash

dir=/usr/local/bin/

jar_name=POPMToRhythmbox.jar

flag=""
for file in "$@"
do
    if [ "$file" = "-f" ]
    then flag="-f"
    else
        if [ "$file" = "-o" ]
        then flag="-o"
        else
            files="$files""\n""$file"
            echo "Adding file ""$file"
        fi
    fi
done

listfile=~/Documents/.rbtopopm_temp.txt
touch $listfile
if [ -f "$listfile" ]
then
    echo "$files" > "$listfile"
fi
java -cp $dir$jar_name POPMToRB "$listfile" "$flag"
