#!/bin/bash

dir=/usr/local/bin/

jar_name=RhythmBoxToPOPM.jar

for file in "$@"
do
files="$files""\n""$file"
echo "Adding file ""$file"
done
listfile=~/Documents/.rbtopopm_temp.txt
touch $listfile
if [ -f "$listfile" ]
then
    echo "$files" > "$listfile"
fi
java -cp $dir$jar_name RBToPOPM "$listfile"
